### ISSUE TITLE
Faltan (aún) universidades

### ISSUE THREAD

**Issue by martinarroyo** [RITSI/MapaTasas#10]
Cimas nos comenta lo siguiente:
- En País Vasco falta Deusto
- Cataluña solo disponemos datos de la Universidad de Barcelona y de la autónoma de Barcelona (faltan UOC,UPC, l?rida, Pompeu Fabra Ramón Llul y Rovira i Virgili)
- En la Rioja falta la internacional
- en Castilla León falta: la Universidad Católica de Santa Teresa de Jesús, la Europea de Miguel de cervantes, Isabel I, la Pontificia de Salamanca, 
- Madrid: faltan Alfonso X el sabio, Antonio de nebrija, Cardenal herrera, europea, miguel de cervantes, UNED años anteriores, universidad a distancia Madrid, Francisco de Vitoria, Menéndez Pelayo (same price as Cantabria), San pablo (I. Información), UTECEM)
- Valencia:  Cardenal herrera, Europea Valencia, Internacional Valencia)

-Murcia: católica san antonio

-Canarias: Fernando Pessoa

-Andalucía: Loyola

**Comment by Ryckes** [comment]
Buen trabajo. Las públicas de Cataluña son todas iguales salvo la UOC, pero la UOC tiene las tasas en el mismo documento, más abajo que el resto. La VIU no la conocía.
