### ISSUE TITLE
Los precios de máster se mezclan con los de grado

### ISSUE THREAD

**Issue by iaguas** [RITSI/MapaTasas#40]
Buenas:

Vamos a ver, fácil. El otro día estábamos actualizando las tasas de grado para que el mapa quedase ya niquelado y podamos por fin lanzarlo sin problema. Entonces, al ir a actualizar las tasas, me dice, ya que tengo los decretos abiertos, vamos a meter también los datos de máster y así tenemos ya todo el trabajo hecho de una sola vez. En principio no debería haber problema, pq como esos datos no se utilizan, simplemente se quedarían en la base de datos para cuando fueran necesarios. Y dejé todo hecho. 

Hoy, al ir al mapa a buscar un tema de Navarra (que es la forma más rápida de acceder a las tasas, para qué nos vamos a engañar), he visto lo siguiente.
![problemas-navarra-master](https://cloud.githubusercontent.com/assets/4259550/24792826/e70684f0-1b7f-11e7-9a24-a054bc27e91c.png)

Como se puede observar, la gráfica hace cosas raras. Después de echarle un vistazo tranquilamente, he llegado a la conclusión que los años que dispone de dos puntos (desde 2015) se debe a que pone tanto los precios públicos de grado como de máster. En cambio, la tabla que se obtiene al situar el ratón encima está bien. De nuevo vuelve a dar problemas al mostrar la fuente de los datos, donde las duplica, algo lógico ya que cada uno de los precios dispone de una forma diferente de adjuntar la dirección en la que se encuentran los datos, pero habría que hacer algo, sobretodo sabiendo que así no queda claro y que ahora mismo, por ser universidades públicas, las fuentes para ambos es la misma (posiblemente no ocurra esto en el caso de las privadas).

A ver qué comentais... ¡un saludo!

**Comment by iaguas** [comment]
Nota: dejo por ahora ambos precios en Navarra. Los retiraré (los de máster) el día que Estudios dé como "hecho" el tema de las tasas.

**Comment by jcabala14** [comment]
Iñigo, el mapa no está preparado para las tasas de master. Se desactivaron precisamente porque no es algo que todavía se puedan contemplar, por lo que no hay que rellenar las tasas de master.

**Comment by iaguas** [comment]
Jorge, ya sé que no esta preparado, aunque pensaba que solo era el tema de mostrarlas. En cualquier caso, reabro esto, algún día hará falta.

**Comment by alexlesaka** [comment]
Después de que la comisión entera decidiera cerrar una tarea y que el coordinador lo haga, no entiendo la insistencia y el saltarse por el forro de los ..... Condones las decisiones para volver a abrirlo. 

Besis

Alex Abuin Yepes
Enviado desde mi iPhone

**Comment by vk496** [comment]
Se debe a que desde Estudios se está trabajando en el tema xD

Salu2 

El 7 de abril de 2017 16:43:22 CEST, alexlesaka <notifications@github.com> escribió:
>Después de que la comisión entera decidiera cerrar una tarea y que el
>coordinador lo haga, no entiendo la insistencia y el saltarse por el
>forro de los ..... Condones las decisiones para volver a abrirlo. 
>
>Besis
>
>Alex Abuin Yepes
>Enviado desde mi iPhone
>
>> El 7 abr 2017, a las 16:29, Iñigo Aguas Ardaiz
><notifications@github.com> escribió:
>> 
>> Jorge, ya sé que no esta preparado, aunque pensaba que solo era el
>tema de mostrarlas. En cualquier caso, reabro esto, algún día hará
>falta.
>> 
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/RITSI/MapaTasas/issues/40#issuecomment-292555985

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by ugedo** [comment]
Si estudios está trabajando en el mapa de tasas me parece estupendo, pero
de momento la comisión decidió no seguir el desarrollo y por tanto no se
estableció un grupo de trabajo para ello. En consecuencia las personas de
la comisión tienen asignada otra tarea diferente al mapa de tasas que
deberían desatender si se centran en esta.

Será cuestión de volver a valorar eso en la próxima reunión si
verdaderamente Estudios está por la labor de darle difusión y uso al mapa.
Evidentemente se tienen que hacer las dos cosas en paralelo, porque tampoco
tiene sentido que una esté a la espera de la otra y viceversa, sería la
pescadilla que se muerde la cola y al final el uno por el otro, las tasas
sin barrer #RefraneroRITSI.

Respecto al tema que nos ocupa, creo que lo sensato sería en todo caso
poner sólo los datos de las tasas de Grado y posteriormente se planteé la
necesidad de preparar el mapa para las tasas de master y ya entonces meter
esos datos, que si Estudios quiere, puede ir recopilando y almacenando en
un documento aparte fuera de la plataforma, para facilitar su adhesión
cuando esté preparada.

Saludos,

Enrique Ugedo Egido
​
Consejero de Gobierno de la UCM
​
Graduado en Ingeniería de Computadores
Becario de Técnico en los Servicios Informáticos de la UCM
Presidente de la Delegación de Alumnos <http://delegacionfdi.fdi.ucm.es/> de
la Facultad de Informática UCM
